name: staticCheck
on:
  pull_request_target:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  static-check:
    uses: reviews-team-test/ci-check-action-static-check/.github/workflows/static-check.yml@static-check
    secrets: inherit