name: staticCheck
on:
  pull_request_target:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  static-check:
    runs-on: ubuntu-latest
    steps:
      - id: change-file-lang
        continue-on-error: true
        uses: reviews-team-test/ci-check-action@get-change-file-lang
      - if: always() && steps.change-file-lang.outputs.isGo == 'true'
        continue-on-error: true
        uses: reviews-team-test/ci-check-action@golangci-lint
      - if: always() && steps.change-file-lang.outputs.isC == 'true'
        continue-on-error: true
        uses: linuxdeepin/action-cppcheck@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          pull_request_id: ${{ github.event.pull_request.number }}
          allow_approve: false
      - if: always() && steps.change-file-lang.outputs.isSh == 'true'
        continue-on-error: true
        uses: reviews-team-test/ci-check-action@shell-check
      - if: always()
        continue-on-error: true
        uses: reviews-team-test/ci-check-action@dbusapi-check
        with:
          reviewers: ckux
